# Get timestamp and user info
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
user <- "hingelman"  # hardcoded as provided

# Create output directories with timestamp
base_dir <- "condition_comparisons"
pdf_dir <- file.path(base_dir, paste0("volcano_plots_", timestamp))
csv_dir <- file.path(base_dir, paste0("csv_files_", timestamp))

# Create directories
dir.create(base_dir, showWarnings = FALSE)
dir.create(pdf_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(csv_dir, recursive = TRUE, showWarnings = FALSE)

# Function to create safe filenames
make_safe_filename <- function(name) {
  gsub("[^a-zA-Z0-9]", "_", name)
}

# Get conditions and reference condition
conditions <- levels(dds$physiological_state)
reference_condition <- conditions[1]  # The first condition is the reference

# Create combinations: reference vs all others + all other pairs
reference_combinations <- lapply(conditions[-1], function(cond) c(cond, reference_condition))
other_combinations <- combn(conditions[-1], 2, simplify = FALSE)
all_combinations <- c(reference_combinations, other_combinations)

# Function to perform DESeq2 analysis and create plots
analyze_pair <- function(condition_pair) {
  condition1 <- condition_pair[1]
  condition2 <- condition_pair[2]
  
  # Create safe filenames
  safe_name1 <- make_safe_filename(condition1)
  safe_name2 <- make_safe_filename(condition2)
  
  # Get results
  res_obj <- results(dds, contrast = c("physiological_state", condition1, condition2))
  
  # Create volcano plot
  pdf_filename <- file.path(pdf_dir, 
                          paste0("volcano_", safe_name1, "vs", safe_name2, ".pdf"))
  
  # Ensure any existing graphics device is closed
  if (dev.cur() != 1) dev.off()
  
  # Create PDF with error handling
  pdf(pdf_filename, width = 10, height = 8)
  tryCatch({
    plot <- EnhancedVolcano(res_obj,
                           lab = rownames(res_obj),
                           x = "log2FoldChange",
                           y = "pvalue",
                           pCutoff = 0.05,
                           FCcutoff = 1.0,
                           title = paste(condition1, "vs", condition2),
                           subtitle = paste0("Volcano plot of differential expression\n",
                                          "Generated by ", user, " at ", 
                                          "2025-05-28 00:56:15 UTC"))  # hardcoded as provided
    print(plot)  # Explicitly print the plot
  }, error = function(e) {
    cat(sprintf("Error creating plot for %s vs %s: %s\n", condition1, condition2, e$message))
  }, finally = {
    dev.off()  # Ensure device is closed
  })
  
  # Save results to CSV
  res_df <- as.data.frame(res_obj)
  csv_filename <- file.path(csv_dir, 
                          paste0("DEG_", safe_name1, "vs", safe_name2, ".csv"))
  write.csv(res_df, csv_filename)
  
  # Create log entry
  cat(sprintf("Completed analysis for %s vs %s\n", condition1, condition2))
  cat(sprintf("- Volcano plot saved as: %s\n", pdf_filename))
  cat(sprintf("- Results saved as: %s\n\n", csv_filename))
}

# Create log file in base directory
log_file <- file.path(base_dir, paste0("DEG_analysis_", timestamp, "_log.txt"))
sink(log_file, split = TRUE)

# Print header
cat("=== Differential Expression Analysis Log ===\n")
cat("Date/Time: 2025-05-28 00:56:15 UTC\n")  # hardcoded as provided
cat(sprintf("User: %s\n", user))
cat(sprintf("PDF Directory: %s\n", normalizePath(pdf_dir)))
cat(sprintf("CSV Directory: %s\n\n", normalizePath(csv_dir)))

# Print reference condition
cat(sprintf("Reference condition: %s\n\n", reference_condition))

# Print conditions
cat("All conditions:\n")
for(cond in conditions) {
  cat(sprintf("- %s%s\n", cond, if(cond == reference_condition) " (reference)" else ""))
}
cat("\n")

# Print planned comparisons
cat("Planned comparisons:\n")
cat("Reference comparisons:\n")
for(pair in reference_combinations) {
  cat(sprintf("- %s vs %s\n", pair[1], pair[2]))
}
cat("\nOther comparisons:\n")
for(pair in other_combinations) {
  cat(sprintf("- %s vs %s\n", pair[1], pair[2]))
}
cat("\n")

# Run analysis for all pairs
invisible(lapply(all_combinations, analyze_pair))

# Print completion message
cat(sprintf("\nAnalysis completed at %s UTC\n", "2025-05-28 00:56:15"))  # hardcoded as provided

# Close log file
sink()

# Print final message to console
cat(sprintf("\nAnalysis complete!\n"))
cat(sprintf("- PDFs saved in: %s\n", normalizePath(pdf_dir)))
cat(sprintf("- CSVs saved in: %s\n", normalizePath(csv_dir)))
cat(sprintf("- Log file: %s\n", normalizePath(log_file)))